### ISSUE TITLE
Not associated as a calendar app

### ISSUE THREAD

**Issue by fthx** [ubuntu/thunderbird#10]
Hi,

It's a longstanding bug, TB snap is not proposed as a calendar default app.
The deb version from Mozilla TB beta PPA makes this association available in GNOME control center.

**Comment by soumyaDghosh** [comment]
![image](https://github.com/ubuntu/thunderbird/assets/72045785/0c07c928-e1fa-4195-9517-1554de7dac2f)

Working for me!

**Comment by fthx** [comment]
Mmmh you do not show TB as a calendar default app!

**Comment by seb128** [comment]
https://discourse.ubuntu.com/t/thunderbird-calendar-in-gnome-shell-default-apps was about that not working in the deb either and it's still not for me in mantic, it's an upstream issue where the .desktop doesn't include x-scheme-handler/calendar or text/calendar

$ grep Mime /usr/share/applications/thunderbird.desktop 
MimeType=x-scheme-handler/mailto;application/x-xpinstall;x-scheme-handler/webcal;x-scheme-handler/mid;message/rfc822;

ii  thunderbird                                1:115.2.3+build2-0ubuntu1                  amd64        Email, RSS and newsgroup client with integrated spam filter

**Comment by seb128** [comment]
It's easy enough to add to the snap desktop so done now

https://github.com/ubuntu/thunderbird/commit/5a71b11a

the next candidate and beta builds should have it

**Comment by fthx** [comment]
Great!

That's odd because I'm 100 % sure that, using TB deb (from Mozilla PPA), I had TB as default calendar app in gnome.
I remember I was happy of this change (I think when upgraded from 102 to 115 in Mozilla PPA).

**Comment by fthx** [comment]
This what is in tb.desktop in current Mantic PPA version:
`MimeType=x-scheme-handler/mailto;application/x-xpinstall;x-scheme-handler/webcal;x-scheme-handler/mid;message/rfc822;`

**Comment by seb128** [comment]
> This what is in tb.desktop in current Mantic PPA version: `MimeType=x-scheme-handler/mailto;application/x-xpinstall;x-scheme-handler/webcal;x-scheme-handler/mid;message/rfc822;`

text/calendar isn't in that list so it would be weird if it was listed...
