### ISSUE TITLE
Build Thunderbird for arm64

### ISSUE THREAD

**Issue by fredldotme** [ubuntu/thunderbird#11]
At Ubuntu Touch there has been some movement about allowing (not pre-installing) Snap support next to our Click format.

Therefore (to supercharge convergent devices like the JingPad and the Fairphone 4 with adequate, often-requested snaps) I would like to know whether there is a roadmap for enabling arm64 (and maybe armhf) devices in the near future?

**Comment by seb128** [comment]
Sorry for the delay replying, the arm64 build got enabled as part of the switch the snap from building from source for Ubuntu 24.04.
